//Libellés Instruments MIDI
//        
const int Nb_Libelle_Midi_Interne = 128;
const int Nb_Libelle_Midi_Externe = 128;
//            Interne            Externe
const String Libelle_Instr_Midi1[128] = { 
                  {"Stereo Grand    "},
                  {"Bright Grand    "},
                  {"Electric Grand  "},
                  {"Honky-Tonk      "},
                  {"Tine Electric Pi"},
                  {"FM Electric Pian"},
                  {"Harpsichord     "},
                  {"Clavinet        "},
                  {"Celeste         "},
                  {"Glockenspiel    "},
                  {"Music Box       "},
                  {"Vibraphone      "},
                  {"Marimba         "},
                  {"Xylophone       "},
                  {"Tubular Bells   "},
                  {"Dulcimer        "},
                  {"Tonewheel Organ "},
                  {"Percussive Organ"},
                  {"Rock Organ      "},
                  {"Pipe Organ      "},
                  {"Reed Organ      "},
                  {"Accordian       "},
                  {"Harmonica       "},
                  {"Bandoneon       "},
                  {"Nylon Guitar    "},
                  {"Steel Guitar    "},
                  {"Jazz Guitar     "},
                  {"Clean Guitar    "},
                  {"Muted Guitar    "},
                  {"Overdrive Guitar"},
                  {"Distortion Guita"},
                  {"Guitar Harmonics"},
                  {"Acoustic Bass   "},
                  {"Finger Bass     "},
                  {"Pick Bass       "},
                  {"Fretless Bass   "},
                  {"Slap Bass 1     "},
                  {"Slap Bass 2     "},
                  {"Synth Bass 1    "},
                  {"Synth Bass 2    "},
                  {"Violin          "},
                  {"Viola           "},
                  {"Cello           "},
                  {"Double Bass     "},
                  {"Stereo Strings T"},
                  {"Pizzicato String"},
                  {"Orchestral Harp "},
                  {"Timpani         "},
                  {"Stereo Strings F"},
                  {"Stereo Strings S"},
                  {"Synth Strings 1 "},
                  {"Synth Strings 2 "},
                  {"Concert Choir   "},
                  {"Voice Oohs      "},
                  {"Synth Voice     "},
                  {"Orchestra Hit   "},
                  {"Trumpet         "},
                  {"Trombone        "},
                  {"Tuba            "},
                  {"Muted Trumpet   "},
                  {"French Horns    "},
                  {"Brass Section   "},
                  {"Synth Brass 1   "},
                  {"Synth Brass 2   "},
                  {"Soprano Sax     "},
                  {"Alto Sax        "},
                  {"Tenor Sax       "},
                  {"Baritone Sax    "},
                  {"Oboe            "},
                  {"English Horn    "},
                  {"Bassoon         "},
                  {"Clarinet        "},
                  {"Piccolo         "},
                  {"Flute           "},
                  {"Recorder        "},
                  {"Pan Flute       "},
                  {"Bottle Blow     "},
                  {"Shakuhachi      "},
                  {"Irish Tin Whistl"},
                  {"Ocarina         "},
                  {"Square Lead     "},
                  {"Saw Lead        "},
                  {"Synth Calliope  "},
                  {"Chiffer Lead    "},
                  {"Charang         "},
                  {"Solo Vox        "},
                  {"5th Saw Wave    "},
                  {"Bass & Lead     "},
                  {"Fantasia        "},
                  {"Warm Pad        "},
                  {"Polysynth       "},
                  {"Space Voice     "},
                  {"Bowed Glass     "},
                  {"Metal Pad       "},
                  {"Halo Pad        "},
                  {"Sweep Pad       "},
                  {"Ice Rain        "},
                  {"Soundtrack      "},
                  {"Crystal         "},
                  {"Atmosphere      "},
                  {"Brightness      "},
                  {"Goblin          "},
                  {"Echo Drops      "},
                  {"Star Theme      "},
                  {"Sitar           "},
                  {"Banjo           "},
                  {"Shamisen        "},
                  {"Koto            "},
                  {"Kalimba         "},
                  {"Bagpipes        "},
                  {"Fiddle          "},
                  {"Shenai          "},
                  {"Tinker Bell     "},
                  {"Agogo           "},
                  {"Steel Drums     "},
                  {"Wood Block      "},
                  {"Taiko Drum      "},
                  {"Melodic Tom     "},
                  {"Synth Drum      "},
                  {"Reverse Cymbal  "},
                  {"Fret Noise      "},
                  {"Breath Noise    "},
                  {"Seashore        "},
                  {"Birds           "},
                  {"Telephone 1     "},
                  {"Helicopter      "},
                  {"Applause        "},
                  {"Gun Shot        "},
                  };
